language: go

go:
 - 1.8.1


cache:
  directories:
    - "$HOME/google-cloud-sdk/"

# Unconditionally place the repo at GOPATH/src/${go_import_path} to support
# forks.
go_import_path: github.com/m-lab/prometheus-support

install:
- go get github.com/prometheus/prometheus/cmd/promtool
- $TRAVIS_BUILD_DIR/travis/install_gcloud.sh kubectl

script:
# Run query "unit tests".
- go test -v github.com/m-lab/prometheus-support/cmd/query_tester -args -log.level warn

# Use promtool to check current alerts and rules. This is only a syntax check.
- promtool check-rules config/federation/prometheus/alerts.yml
- promtool check-rules config/federation/prometheus/rules.yml

# TODO(soltesz): support check-config.
# promtool check-config config/federation/prometheus/prometheus.yml
# promtool check-config config/cluster/prometheus/prometheus.yml

deploy:
#########################################
## Sandbox
- provider: script
  script: $TRAVIS_BUILD_DIR/kubectl.sh mlab-sandbox prometheus-federation ./apply-global-prometheus.sh
  skip_cleanup: true
  on:
    repo: m-lab/prometheus-support
    all_branches: true
    condition: $TRAVIS_BRANCH == sandbox-* && $TRAVIS_EVENT_TYPE == push

- provider: script
  script: $TRAVIS_BUILD_DIR/kubectl.sh mlab-sandbox scraper-cluster ./apply-cluster.sh
  skip_cleanup: true
  on:
    repo: m-lab/prometheus-support
    all_branches: true
    condition: $TRAVIS_BRANCH == sandbox-* && $TRAVIS_EVENT_TYPE == push

#########################################
## Staging
- provider: script
  script: $TRAVIS_BUILD_DIR/kubectl.sh mlab-staging prometheus-federation ./apply-global-prometheus.sh
  skip_cleanup: true
  on:
    repo: m-lab/prometheus-support
    all_branches: true
    condition: $TRAVIS_BRANCH == master && $TRAVIS_EVENT_TYPE == push

- provider: script
  script: $TRAVIS_BUILD_DIR/kubectl.sh mlab-staging scraper-cluster ./apply-cluster.sh
  skip_cleanup: true
  on:
    repo: m-lab/prometheus-support
    all_branches: true
    condition: $TRAVIS_BRANCH == master && $TRAVIS_EVENT_TYPE == push

#########################################
## Production
# TODO: add deploy on tags.

before_install:
- travis/decrypt.sh "$encrypted_1c8dd3704323_key" "$encrypted_1c8dd3704323_iv"
  keys/service-accounts.tar.enc /tmp/service-accounts.tar /tmp
