apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9090'
  name: prometheus-public-service
  namespace: default
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    # Pods with labels matching this key/value pair will be publically
    # accessible through the service IP and port.
    run: prometheus-server
  sessionAffinity: None
  # Allocate a static IP manually in GCP console: Networking -> Load Balancing.
  externalIPs:
    - 35.184.247.140
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    # The grafana web server does not export any prometheus metrics.
    prometheus.io/scrape: 'false'
  name: grafana-public-service
  namespace: default
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    # Pods with labels matching this key/value pair will be publically
    # accessible through the service IP and port.
    run: grafana-server
  sessionAffinity: None
  # Use the same static IP as used for Prometheus.
  externalIPs:
    # Use the same IP as above, since we're on a different port.
    - 35.184.247.140
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9093'
  name: alertmanager-public-service
  namespace: default
spec:
  ports:
  - port: 9093
    protocol: TCP
    targetPort: 9093
  selector:
    # Pods with labels matching this key/value pair will be publically
    # accessible through the service IP and port.
    run: alertmanager-server
  sessionAffinity: None
  # Use the same static IP as used for Prometheus.
  externalIPs:
    # Use the same IP as above, since we're on a different port.
    - 35.184.247.140
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    # The grafana web server does not export any prometheus metrics.
    prometheus.io/scrape: 'false'
  name: blackbox-public-service
  namespace: default
spec:
  ports:
  - port: 9115
    protocol: TCP
    targetPort: 9115
  selector:
    # Pods with labels matching this key/value pair will be publically
    # accessible through the service IP and port.
    run: blackbox-server
  sessionAffinity: None
  # Use the same static IP as used for Prometheus.
  externalIPs:
    # Use the same IP as above, since we're on a different port.
    - 35.184.247.140
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: pushgateway-public-service
  namespace: default
spec:
  ports:
  - port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    # Pods with labels matching this key/value pair will be publically
    # accessible through the service IP and port.
    run: pushgateway-server
  sessionAffinity: None
  # Use the same static IP as used for Prometheus.
  externalIPs:
    # Use the same IP as above, since we're on a different port.
    - 35.184.247.140
  type: ClusterIP
