apiVersion: apps/v1
kind: Deployment
metadata:
  name: rebot
spec:
  replicas: 1
  selector:
    matchLabels:
      run: rebot
  template:
    metadata:
      labels:
        run: rebot
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: rebot
        image: measurementlab/rebot:v0.2.1
        imagePullPolicy: Always
        args:
          - "-project={{GCLOUD_PROJECT}}"
          - "-reboot.username={{REBOOTAPI_USER}}"
          - "-reboot.password={{REBOOTAPI_PASS}}"
          - "-reboot.addr=https://reboot.{{GCLOUD_PROJECT}}.measurementlab.net"
          - "-prometheus.username={{PROM_AUTH_USER}}"
          - "-prometheus.password={{PROM_AUTH_PASS}}"
        resources:
          limits:
            cpu: 200m
            memory: 50Mi
          requests:
            cpu: 200m
            memory: 50Mi
        ports:
          - containerPort: 9990
