apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: snmp-exporter
spec:
  # Run two so that we can make sure we have failover.
  replicas: 2
  selector:
    matchLabels:
      run: snmp-exporter
  template:
    metadata:
      labels:
        run: snmp-exporter
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      # Do an early fetch of the configuration so that snmp-exporter will start
      initContainers:
      - name: gcs-downloader-once
        image: measurementlab/gcs-downloader:v0.1
        args:
        - -source=gs://switch-config-{{GCLOUD_PROJECT}}/snmp_exporter_config.yaml
        - -output=/config
        - -once
        volumeMounts:
        - mountPath: /config
          name: snmp-exporter-storage
      containers:
      - name: snmp-exporter
        image: prom/snmp-exporter:v0.13.0
        args:
        - --config.file=/etc/snmp_exporter/snmp_exporter_config.yaml
        ports:
        - containerPort: 9116
        volumeMounts:
        - mountPath: /etc/snmp_exporter
          name: snmp-exporter-storage
      # Pull the snmp-exporter configuration from GCS every 5 minutes.
      - name: gcs-downloader
        image: measurementlab/gcs-downloader:v0.1
        args:
        - -source=gs://switch-config-{{GCLOUD_PROJECT}}/snmp_exporter_config.yaml
        - -output=/config
        - -period=5
        resources:
          requests:
            memory: "150Mi"
            cpu: "50m"
          limits:
            memory: "150Mi"
            cpu: "50m"
        volumeMounts:
        # Mount snmp-exporter-storage for write access to the snmp_exporter configuration.
        - mountPath: /config
          name: snmp-exporter-storage
      # Check https://hub.docker.com/r/jimmidyson/configmap-reload/tags/ for the current
      # stable version.
      - image: jimmidyson/configmap-reload:v0.2.2
        name: configmap-reload
        args: ["-webhook-url", "http://localhost:9116/-/reload",
               "-volume-dir", "/config"]
        resources:
          requests:
            memory: "400Mi"
            cpu: "200m"
          limits:
            memory: "400Mi"
            cpu: "200m"
        volumeMounts:
        # Mount the snmp-exporter config volume so we can watch it for changes.
        - mountPath: /config
          name: snmp-exporter-storage
      # The snmp-exporter will only be scheduled onto nodes that we labeled
      # as having a static outbound IP.
      nodeSelector:
        outbound-ip: static
      # We can also taint nodes with static outbound IPs so that services that
      # do not require a static IP aren't scheduled to that node. This
      # deployment, however, will tolerate that taint.
      tolerations:
      - key: "outbound-ip"
        value: "static"
        effect: "NoSchedule"
      # Use an emptyDir volume just to share config between containers.
      volumes:
      - name: snmp-exporter-storage
        emptyDir: {}
