apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: snmp-exporter
spec:
  # Run two so that we can make sure we have failover.
  replicas: 2
  selector:
    matchLabels:
      run: snmp-exporter
  template:
    metadata:
      labels:
        run: snmp-exporter
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: run
                operator: In
                values:
                - snmp-exporter
            topologyKey: kubernetes.io/hostname
      containers:
      - name: snmp-exporter
        image: prom/snmp-exporter:v0.15.0
        args:
        - --config.file=/etc/snmp_exporter/snmp_exporter_config.yaml
        ports:
        - containerPort: 9116
        volumeMounts:
        - mountPath: /etc/snmp_exporter
          name: snmp-exporter-config
      # Check https://hub.docker.com/r/jimmidyson/configmap-reload/tags/ for the current
      # stable version.
      - image: jimmidyson/configmap-reload:v0.2.2
        name: configmap-reload
        args: ["-webhook-url", "http://localhost:9116/-/reload",
               "-volume-dir", "/config"]
        resources:
          requests:
            memory: "400Mi"
            cpu: "200m"
          limits:
            memory: "400Mi"
            cpu: "200m"
        volumeMounts:
        # Mount the snmp-exporter config volume so we can watch it for changes.
        - mountPath: /config
          name: snmp-exporter-config
      # The snmp-exporter will only be scheduled onto nodes that we labeled
      # as having a static outbound IP.
      nodeSelector:
        outbound-ip: static
      # We can also taint nodes with static outbound IPs so that services that
      # do not require a static IP aren't scheduled to that node. This
      # deployment, however, will tolerate that taint.
      tolerations:
      - key: "outbound-ip"
        value: "static"
        effect: "NoSchedule"
      volumes:
      - name: snmp-exporter-config
        configMap:
          name: snmp-exporter-config
