apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auto-prometheus-disk0
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{PROMETHEUS_VOLUME_SIZE}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auto-grafana-disk0
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auto-alertmanager-disk0
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
