# Configuration values for mlab-sandbox.

GCLOUD_PROJECT: mlab-sandbox
PROMETHEUS_RAM: 42Gi
PROMETHEUS_CPU: 10000m
PROMETHEUS_VOLUME_SIZE: 200Gi
EXTERNAL_IP: 35.184.166.181
TLS_EMAIL: support@measurementlab.net
TLS_IP: 35.226.80.19
GITHUB_RECEIVER_INMEMORY: true
