# Configuration values for mlab-oti

GCLOUD_PROJECT: mlab-oti
LOCATE_PROJECT: mlab-ns
PROMETHEUS_RAM: 42Gi
PROMETHEUS_CPU: 10000m
PROMETHEUS_VOLUME_SIZE: 400Gi
EXTERNAL_IP: 35.184.81.106
TLS_ISSUER: letsencrypt
TLS_EMAIL: support@measurementlab.net
TLS_IP: 35.194.63.109
GITHUB_RECEIVER_INMEMORY: false
