apiVersion: v1
kind: Service
metadata:
  name: github-receiver-public-service
  namespace: default
spec:
  ports:
  - port: 9393
    protocol: TCP
    targetPort: 9393
  selector:
    # Pods with labels matching this key/value pair will be publically
    # accessible through the service IP and port.
    run: github-receiver
  sessionAffinity: None
  type: ClusterIP
